# Run tests then upload to Pypi on version bumps.
# Run tests on each push.
# Try to bump version
# If version is bumped, upload to pypi or test.pypi depending on branch name.

name: pypi project

on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [master]

jobs:

  # Deploy on test.pypi when branch is dev and commit message starts with 'bump'
  deploy-on-testpypi:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: github.ref_name == 'dev' && startsWith(github.event.head_commit.message, 'bump:')
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          repository_url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}

  # Deploy on pypi when branch is master and commit message starts with 'bump'
  deploy-on-pypi:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: github.ref_name == 'master' && startsWith(github.event.head_commit.message, 'bump:')
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
